# This file was generated by GoReleaser. DO NOT EDIT.
cask "nsql" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/nsql"]
    end
  end

  version "0.1.14"

  on_macos do
    on_arm do
      sha256 "44604963278bc13740d8cae66e071a9823cc7758eaeff505c10d69c72ebacbe7"
      url "https://github.com/fredrir/nsql/releases/download/v#{version}/nsql-aarch64-apple-darwin-v#{version}.tar.gz"
    end
    on_intel do
      sha256 "db55df561ce8a529ec838dccee1b09cc99ee3aae6d1b98afade121002ec0eb84"
      url "https://github.com/fredrir/nsql/releases/download/v#{version}/nsql-x86_64-apple-darwin-v#{version}.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f195dd8ade18f835f5cb0c46cb99085a9c87a250d85a06e30ab1e5cf9a529924"
      url "https://github.com/fredrir/nsql/releases/download/v#{version}/nsql-aarch64-unknown-linux-musl-v#{version}.tar.gz"
    end
    on_intel do
      sha256 "27e02223721dba8a3b4556b22f362d6ea5eafe6bff22100ac5a1a7d23b2348f8"
      url "https://github.com/fredrir/nsql/releases/download/v#{version}/nsql-x86_64-unknown-linux-musl-v#{version}.tar.gz"
    end
  end

  name "nsql"
  desc "Run SQL from your terminal, composed in your real neovim — without taking over the screen."
  homepage "https://github.com/fredrir/nsql"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nsql"

  # No zap stanza required
end
